### ISSUE TITLE
OSX

### ISSUE THREAD

**Issue by dataf3l** [tony-o/perl6-http-server-threaded#3] opened 2016-11-02 07:34 UTC
when I install, tests fail, when I install with --notests and try to run the basic example, I get this:

Felipes-MacBook-Pro:backend2 a$ panda --notests install HTTP::Server::Threaded
==> Fetching HTTP::Server::Threaded
==> Building HTTP::Server::Threaded
==> Installing HTTP::Server::Threaded
==> Successfully installed HTTP::Server::Threaded
Felipes-MacBook-Pro:backend2 a$ perl6 threaded.p6 
Cannot directly create a Supply. You might want:
 - To use a Supplier in order to get a live supply
 - To use Supply.on-demand to create an on-demand supply
 - To create a Supply using a supply block
  in method  at /usr/local/Cellar/rakudo-star/2016.07/share/perl6/site/sources/3CA3A94E8EC6BDFE95FC1E93CCDF60DD679B9836 (HTTP::Server::Threaded) line 9
  in block <unit> at threaded.p6 line 3

**Comment by dataf3l** [comment] 2016-11-02 07:35
Felipes-MacBook-Pro:backend2 a$ panda install HTTP::Server::Threaded
==> Fetching HTTP::Server::Threaded
==> Building HTTP::Server::Threaded
==> Testing HTTP::Server::Threaded
===SORRY!=== Error while compiling /Users/a/Desktop/ab/htdocs/gis/backend2/.panda-work/1478072106_1/t/lib/starter.pm6 (starter)
'use lib' may not be pre-compiled
at /Users/a/Desktop/ab/htdocs/gis/backend2/.panda-work/1478072106_1/t/lib/starter.pm6 (starter):4
------> use lib 'lib'⏏;
t/01_request.t .................... 
Dubious, test returned 1 (wstat 256, 0x100)
No subtests run 
===SORRY!=== Error while compiling /Users/a/Desktop/ab/htdocs/gis/backend2/.panda-work/1478072106_1/t/lib/starter.pm6 (starter)
'use lib' may not be pre-compiled
at /Users/a/Desktop/ab/htdocs/gis/backend2/.panda-work/1478072106_1/t/lib/starter.pm6 (starter):4
------> use lib 'lib'⏏;
t/02_plugins.t .................... 
Dubious, test returned 1 (wstat 256, 0x100)
No subtests run 
===SORRY!=== Error while compiling /Users/a/Desktop/ab/htdocs/gis/backend2/.panda-work/1478072106_1/t/lib/starter.pm6 (starter)
'use lib' may not be pre-compiled
at /Users/a/Desktop/ab/htdocs/gis/backend2/.panda-work/1478072106_1/t/lib/starter.pm6 (starter):4
------> use lib 'lib'⏏;
t/03_statuscode.t ................. 
Dubious, test returned 1 (wstat 256, 0x100)
No subtests run 
===SORRY!=== Error while compiling /Users/a/Desktop/ab/htdocs/gis/backend2/.panda-work/1478072106_1/t/lib/starter.pm6 (starter)
'use lib' may not be pre-compiled
at /Users/a/Desktop/ab/htdocs/gis/backend2/.panda-work/1478072106_1/t/lib/starter.pm6 (starter):4
------> use lib 'lib'⏏;
t/04_unbuffered_laggy_response.t .. 
Dubious, test returned 1 (wstat 256, 0x100)
No subtests run 
===SORRY!=== Error while compiling /Users/a/Desktop/ab/htdocs/gis/backend2/.panda-work/1478072106_1/t/lib/starter.pm6 (starter)
'use lib' may not be pre-compiled
at /Users/a/Desktop/ab/htdocs/gis/backend2/.panda-work/1478072106_1/t/lib/starter.pm6 (starter):4
------> use lib 'lib'⏏;
t/05_laggyrequest.t ............... 
Dubious, test returned 1 (wstat 256, 0x100)
No subtests run 
===SORRY!=== Error while compiling /Users/a/Desktop/ab/htdocs/gis/backend2/.panda-work/1478072106_1/t/lib/starter.pm6 (starter)
'use lib' may not be pre-compiled
at /Users/a/Desktop/ab/htdocs/gis/backend2/.panda-work/1478072106_1/t/lib/starter.pm6 (starter):4
------> use lib 'lib'⏏;
t/07_chunkedrequestecho.t ......... 
Dubious, test returned 1 (wstat 256, 0x100)
No subtests run 
===SORRY!=== Error while compiling /Users/a/Desktop/ab/htdocs/gis/backend2/.panda-work/1478072106_1/t/lib/starter.pm6 (starter)
'use lib' may not be pre-compiled
at /Users/a/Desktop/ab/htdocs/gis/backend2/.panda-work/1478072106_1/t/lib/starter.pm6 (starter):4
------> use lib 'lib'⏏;
t/09_unbuffer.t ................... 
Dubious, test returned 1 (wstat 256, 0x100)
No subtests run 

## Test Summary Report

t/01_request.t                  (Wstat: 256 Tests: 0 Failed: 0)
  Non-zero exit status: 1
  Parse errors: No plan found in TAP output
t/02_plugins.t                  (Wstat: 256 Tests: 0 Failed: 0)
  Non-zero exit status: 1
  Parse errors: No plan found in TAP output
t/03_statuscode.t               (Wstat: 256 Tests: 0 Failed: 0)
  Non-zero exit status: 1
  Parse errors: No plan found in TAP output
t/04_unbuffered_laggy_response.t (Wstat: 256 Tests: 0 Failed: 0)
  Non-zero exit status: 1
  Parse errors: No plan found in TAP output
t/05_laggyrequest.t             (Wstat: 256 Tests: 0 Failed: 0)
  Non-zero exit status: 1
  Parse errors: No plan found in TAP output
t/07_chunkedrequestecho.t       (Wstat: 256 Tests: 0 Failed: 0)
  Non-zero exit status: 1
  Parse errors: No plan found in TAP output
t/09_unbuffer.t                 (Wstat: 256 Tests: 0 Failed: 0)
  Non-zero exit status: 1
  Parse errors: No plan found in TAP output
Files=7, Tests=0,  3 wallclock secs ( 0.04 usr  0.02 sys +  2.50 cusr  0.48 csys =  3.04 CPU)
Result: FAIL
The spawned process exited unsuccessfully (exit code: 1)
  in sub run-and-gather-output at /usr/local/Cellar/rakudo-star/2016.07/share/perl6/site/sources/24811C576EF8F85E7672B26955C802BB2FC94675 (Panda::Common) line 85
  in block  at /usr/local/Cellar/rakudo-star/2016.07/share/perl6/site/sources/48E2EB9144E069353B240AD2D147B48C65F70152 (Panda::Tester) line 22
  in sub indir at /usr/local/Cellar/rakudo-star/2016.07/share/perl6/site/sources/24811C576EF8F85E7672B26955C802BB2FC94675 (Panda::Common) line 20
  in method test at /usr/local/Cellar/rakudo-star/2016.07/share/perl6/site/sources/48E2EB9144E069353B240AD2D147B48C65F70152 (Panda::Tester) line 5
  in method install at /usr/local/Cellar/rakudo-star/2016.07/share/perl6/site/sources/582CB7486602954A4601BDCE5A0EAC54B05DA58A (Panda) line 156
  in method resolve at /usr/local/Cellar/rakudo-star/2016.07/share/perl6/site/sources/582CB7486602954A4601BDCE5A0EAC54B05DA58A (Panda) line 234
  in sub MAIN at /usr/local/Cellar/rakudo-star/2016.07/share/perl6/site/resources/E0D978079BB5081DE986D058BB8AB08252F05CC8 line 18
  in block <unit> at /usr/local/Cellar/rakudo-star/2016.07/share/perl6/site/resources/E0D978079BB5081DE986D058BB8AB08252F05CC8 line 151

**Comment by gfldex** [comment] 2016-11-02 12:18
The issue is unrelated to OSX. PR pending.

**Comment by tony-o** [comment] 2016-11-04 18:12
@dataf3l @gfldex Merged and commited some updates that should correct this module's issues.

**Closed as completed** 2019-02-12 07:02 UTC
